<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>MdbToSql.AccessApplication</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MdbToSql.Core\MdbToSql.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="MdbToSql.Tests" />
  </ItemGroup>
</Project>
